// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG5x7atwPtUFsXFwLpWpkcuhAHuic0xHo',
    appId: '1:957763039460:web:182c856c7bc83e74dd3cf1',
    messagingSenderId: '957763039460',
    projectId: 'notelearn-7b69c',
    authDomain: 'notelearn-7b69c.firebaseapp.com',
    storageBucket: 'notelearn-7b69c.firebasestorage.app',
    measurementId: 'G-Q3JWTF26T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRkjf_vnMv0Qv5jgPn1YhSP06xB11ZXv4',
    appId: '1:957763039460:android:d39976a4f142b773dd3cf1',
    messagingSenderId: '957763039460',
    projectId: 'notelearn-7b69c',
    storageBucket: 'notelearn-7b69c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXOqF93GJyy-7QLKLlY_vFdb-SRx8fxrs',
    appId: '1:957763039460:ios:c81a61ecd5e2e3d5dd3cf1',
    messagingSenderId: '957763039460',
    projectId: 'notelearn-7b69c',
    storageBucket: 'notelearn-7b69c.firebasestorage.app',
    iosBundleId: 'com.example.notelearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXOqF93GJyy-7QLKLlY_vFdb-SRx8fxrs',
    appId: '1:957763039460:ios:c81a61ecd5e2e3d5dd3cf1',
    messagingSenderId: '957763039460',
    projectId: 'notelearn-7b69c',
    storageBucket: 'notelearn-7b69c.firebasestorage.app',
    iosBundleId: 'com.example.notelearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG5x7atwPtUFsXFwLpWpkcuhAHuic0xHo',
    appId: '1:957763039460:web:994e4baa21f60b57dd3cf1',
    messagingSenderId: '957763039460',
    projectId: 'notelearn-7b69c',
    authDomain: 'notelearn-7b69c.firebaseapp.com',
    storageBucket: 'notelearn-7b69c.firebasestorage.app',
    measurementId: 'G-PH8YTN6T6M',
  );
}
